import { Comfortaa, Lexend } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/layout/AdminSidebar";
import AdminNavbar from "@/components/layout/AdminNavbar";
import ProtectedAdmin from "./ProtectedAdmin";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${comfortaa.variable} ${lexend.variable} font-Lexend`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        <ProtectedAdmin>
          <section className="flex w-full h-screen overflow-hidden">
            <AdminSidebar />
            <div className="flex flex-col flex-1 h-screen overflow-hidden">
              <AdminNavbar />
              <div className="flex-1 overflow-y-auto px-4 py-2">
                <ToastContainer />
                {children}
              </div>
            </div>
          </section>
        </ProtectedAdmin>
      </body>
    </html>
  );
}
