import { Geist, Geist_Mono, Comfortaa, Lexend } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/layout/AdminSidebar";
import AdminNavbar from "@/components/layout/AdminNavbar";
import Navbar from "@/components/layout/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // or any you need
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comfortaa.variable} ${lexend.variable} font-lexend`}>
        <section className="flex">
          <AdminSidebar />
          <div className="w-full">
            <AdminNavbar />
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
