#version: '3.8'

services:
  # ──────────────────────────────
  # PostgreSQL
  # ──────────────────────────────
  postgres:
    container_name: nnine-helicar-db
    image: postgres:15
    restart: always
    env_file:
      - /home/azureuser/client-project/helicarbooking/server/.env   # ← reads DB_* vars
    environment:
      POSTGRES_DB:       ${DB_NAME}        # pulled from the same env_file
      POSTGRES_USER:     ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-32807}:5432"           # default if DB_PORT not set
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - helicar-network

  # ──────────────────────────────
  # Backend (Node.js + Sequelize)
  # ──────────────────────────────
  nnine-helicar-be:
    container_name: nnine-helicar-be
    image: prina1/nnine-helicar-be:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - /home/azureuser/client-project/helicarbooking/server/.env
    environment:               # overrides / additions for inside‑container use
      DB_HOST: postgres        # service name of the Postgres container
      DB_PORT: 5432            # internal port; keep fixed
    ports:
      - "4000:4000"
    networks:
      - helicar-network

# ──────────────────────────────
# Docker objects
# ──────────────────────────────
volumes:
  postgres-data:

networks:
  helicar-network:
    driver: bridge
