# version: '3.8'

services:
  postgres:
    container_name: nnine-helicar-db
    image: postgres:15
    restart: always
    env_file:
      - .env                       # ← loads DB_NAME / DB_USERNAME / DB_PASSWORD
    environment:                   # map them to Postgres variables
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"          # external host port → internal 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - helicar-network

  nnine-helicar-be:
    container_name: nnine-helicar-be
    image: prina1/nnine-helicar-be:latest
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env                       # pull in all app settings
    environment:                   # overrides that must differ inside Docker
      DB_HOST: postgres            # service name of postgres container
      DB_PORT: 5432                # fixed internal port
    ports:
      - "4000:4000"
    networks:
      - helicar-network

volumes:
  postgres-data:

networks:
  helicar-network:
    driver: bridge
