import { Comfortaa, Lexend } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Helicar",
  description: "Generated by create next app",
};

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${comfortaa.variable} ${lexend.variable} font-Lexend`}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        {children}
      </body>
    </html>
  );
}
