import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "../globals.css";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} font-Lexend`}
        suppressContentEditableWarning
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
