name: LintPR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  issues:
    types:
      - opened
      
permissions:
  contents: write
  pull-requests: write
  
jobs:
  validate-pr-title:
    name: Lint PR 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amannn/action-semantic-pull-request@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

            #  lint-pr:
            #    name: Lint PR
            #    runs-on: ubuntu-latest
            #    steps:
            #      - uses: actions/checkout@v2
            #      - uses: amannn/action-semantic-pull-request@v5.1.0
            #        env:
            #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #        with:
            #          validateSingleCommit: true
            #          validateSingleCommitMatchesPrTitle: true
